FROM nginx:alpine

# Copiar el script de inicio
COPY start.sh /start.sh
RUN chmod +x /start.sh

# Copiar la aplicación compilada previamente
COPY dist/catalogo-peliculas /usr/share/nginx/html

# Exponer puerto 
EXPOSE 8080

# Ejecutar script de inicio
CMD ["/start.sh"]
